# Generated by Django 5.0.4 on 2024-04-13 10:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='login',
        ),
        migrations.RemoveField(
            model_name='signup',
            name='con_password',
        ),
    ]
