# Generated by Django 5.0.4 on 2024-05-19 18:16

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0005_rename_name_sub_subcategory_name_brand_user_orderlog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderlog',
            name='ordedr_time',
            field=models.DateTimeField(default=datetime.datetime(2024, 5, 19, 23, 46, 11, 904706)),
        ),
    ]
