# Generated by Django 5.0.4 on 2024-05-20 13:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0007_brand_email_alter_orderlog_ordedr_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='brand',
            name='email',
        ),
        migrations.AlterField(
            model_name='orderlog',
            name='ordedr_time',
            field=models.DateTimeField(default=datetime.datetime(2024, 5, 20, 19, 11, 45, 387375)),
        ),
    ]
