# Generated by Django 5.0.4 on 2024-05-20 13:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0008_remove_brand_email_alter_orderlog_ordedr_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='available_count',
        ),
        migrations.AddField(
            model_name='product',
            name='L_stock',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='product',
            name='M_stock',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='product',
            name='S_stock',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='product',
            name='XL_stock',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='product',
            name='XS_stock',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='product',
            name='XXL_stock',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='product',
            name='available_stock',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='orderlog',
            name='ordedr_time',
            field=models.DateTimeField(default=datetime.datetime(2024, 5, 20, 19, 24, 6, 106675)),
        ),
    ]
