# Generated by Django 5.0.4 on 2024-05-20 16:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0011_alter_orderlog_ordedr_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderlog',
            name='ordedr_time',
        ),
        migrations.AddField(
            model_name='orderlog',
            name='ordered_time',
            field=models.DateTimeField(default=datetime.datetime(2024, 5, 20, 22, 2, 36, 639026)),
        ),
    ]
