# Generated by Django 5.0.4 on 2024-05-20 17:26

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0016_alter_orderlog_ordered_time_alter_productimage_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderlog',
            name='ordered_time',
            field=models.DateTimeField(default=datetime.datetime(2024, 5, 20, 22, 56, 14, 446199)),
        ),
    ]
