# Generated by Django 5.0.4 on 2024-05-20 17:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('application', '0017_alter_orderlog_ordered_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderlog',
            name='ordered_time',
            field=models.DateTimeField(default=datetime.datetime(2024, 5, 20, 23, 22, 19, 356409)),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='image',
            field=models.ImageField(upload_to='images/product_images/'),
        ),
    ]
